//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.BookIssuance = new HashSet<BookIssuance>();
            this.BookLost = new HashSet<BookLost>();
        }
    
        public int Id { get; set; }
        public int PublisherId { get; set; }
        public int BookId { get; set; }
        public int BBK_Id { get; set; }
        public int YDK_Id { get; set; }
        public int Year { get; set; }
        public int Pages { get; set; }
        public string ISBN { get; set; }
        public string Article { get; set; }
        public string Record { get; set; }
        public int Count { get; set; }
        public int Left { get; set; }
        public string ImagePath { get; set; }
    
        public virtual BBK BBK { get; set; }
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookIssuance> BookIssuance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookLost> BookLost { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual YDK YDK { get; set; }
    }
}
